modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Viola-Siemens/Instrument-Plus-Plus/issues"

[[mods]]
modId="ipp"
version="${file.jarVersion}"
displayName="Instrument++"
logoFile="logo.png"
credits="Liu Dongyu"
authors="Hexagram"

description='''
More Musical Instruments for Note Blocks!
'''

[[dependencies.ipp]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ipp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
